Update CI build and add badges to readme
Jmeyer1292/opw_kinematics pull request #43
Opened 2020-10-08 02:26 UTC by Levi-Armstrong

2020-10-08 20:08 UTC, Levi-Armstrong commented
@marip8 Also include if you have time to review.

2020-10-08 23:33 UTC, marip8 requested changes

2020-10-08 23:33 UTC, marip8 commented on .github/workflows/xenial_build.yml
> +      - uses: actions/checkout@v1
Use checkout@v2

2020-10-08 23:33 UTC, marip8 commented on .github/workflows/focal_build.yml
> +      - uses: actions/checkout@v1
Use checkout@v2

2020-10-08 23:33 UTC, marip8 commented on .github/workflows/clang_format.yml
> +      - uses: actions/checkout@v1
Use checkout@v2

2020-10-08 23:33 UTC, marip8 commented on .github/workflows/bionic_build.yml
> +      - uses: actions/checkout@v1
Use checkout@v2

2020-10-09 00:24 UTC, Levi-Armstrong commented
@marip8 Update the checkout to v2.

2020-10-09 14:06 UTC, marip8 approved these changes

2020-10-09 14:07 UTC, merged

2020-10-09 14:07 UTC, Levi-Armstrong commented
Thank you for the review @marip8